fn main() {
    int[] nums = [1,2,3,4]
    str world = "world"

    for n in nums {
        print(n)
    }

    say_hello("world")
    say_hello()

    const person = Person{name:"chris"}
    person.say_hello()
}

// optional parameters
fn say_hello(str? world) {
    str subject = world or "sads"
    print("Hello, {subject}!")
}

Person :: struct {
    name str
    email str?
}

Person :: say_hello(self) {
    print("hello {self.name}")
}



